name: CI
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  ci:
    name: Run CI Task
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create mount directories
        run: |
          mkdir -p ~/.claude ~/.config/opencode ~/.local/share/opencode

      - name: Run CI Task
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: /bin/bash -c "task ci"
